export default {
  remembered: {
    Tesseract: {
      0: {
        shape: 'tesseract',
        colors: 'onedarkterminator',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 1.25,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.1,
        blending: 2,
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.04,
        blending: 2,
        linewidth: 2,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    Pentachoron: {
      0: {
        shape: 'pentachoron',
        colors: 'material',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 1.5,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.15,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.04,
        blending: 2,
        linewidth: 1,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    Hexadecachoron: {
      0: {
        shape: 'hexadecachoron',
        colors: 'onedarkterminator',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3.5,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.08,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.05,
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Icositetrachoron (24-cell)': {
      0: {
        shape: 'icositetrachoron',
        colors: 'material',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3.5,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.15,
        blending: '1',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.25,
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Hecatonicosachoron (120-cell)': {
      0: {
        shape: 'hecatonicosachoron',
        colors: 'onedarkterminator',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 0.6,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.05,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.05,
        blending: '2',
        linewidth: 1.25,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Hexacosichoron (600-cell)': {
      0: {
        shape: 'hexacosichoron',
        colors: 'sweetlove',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3.5,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.1,
        blending: '1',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.25,
        blending: '2',
        linewidth: 1,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Grand Antiprism': {
      0: {
        shape: 'grandAntiPrism',
        colors: 'onedarkterminator',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3.5,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.035,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.02,
        blending: '2',
        linewidth: 2,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Cubic Pyramid': {
      0: {
        shape: 'cubicPyramid',
        colors: 'onedarkterminator',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 1.5,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 5,
        xz: 5,
        xw: 10,
        yz: 5,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.3,
        blending: '1',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.5,
        blending: '2',
        linewidth: 2.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    SolidTesseract: {
      0: {
        shape: 'tesseract',
        colors: 'material',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 1.25,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 1,
        blending: 0,
        depthWrite: true,
      },
      4: {
        visible: false,
        opacity: 0.04,
        blending: 2,
        linewidth: 2,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    NeonTesseract: {
      0: {
        shape: 'tesseract',
        colors: 'zenburn',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 1.25,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.05,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 1,
        blending: '0',
        linewidth: 5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    '3-sphere': {
      0: {
        shape: 'glome',
        colors: 'zenburn',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.2,
        blending: '1',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: false,
        opacity: 0.1,
        blending: '2',
        linewidth: 0.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    '3-torus': {
      0: {
        shape: 'diTorus',
        colors: 'zenburn',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 2,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.3,
        blending: '1',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.05,
        blending: '2',
        linewidth: 0.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    '3-sphere-edges': {
      0: {
        shape: 'glome',
        colors: 'zenburn',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: false,
        opacity: 0.05,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.1,
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    '3-sphere-minecraft': {
      0: {
        shape: 'glome',
        colors: 'sweetlove',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 3,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 1,
        blending: '0',
        depthWrite: true,
        wireframe: false,
      },
      4: {
        visible: false,
        opacity: 0.1,
        blending: '2',
        linewidth: 0.5,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    "Klein's Bottle": {
      0: {
        shape: 'generateUVSurface',
        colors: 'zenburn',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 2.5,
        x: '0.75 * (cos(u / 2) * cos(v) - sin(u/2) * sin(2*v))',
        y: '0.75 * (sin(u / 2) * cos(v) + cos(u/2) * sin(2*v))',
        z: '0.75 * cos(u) * (1 + 0.001 * sin(v))',
        w: '0.75 * sin(u) * (1 + 0.001 * sin(v))',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: true,
        uLoop: false,
        uResolution: 38,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: true,
        vLoop: true,
        vResolution: 38,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 5,
        xz: 5,
        xw: 5,
        yz: 5,
        yw: 5,
        zw: 5,
      },
      3: {
        visible: true,
        opacity: 0.25,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.1,
        blending: '1',
        linewidth: 1,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Mobius Tube': {
      0: {
        shape: 'generateUVSurface',
        colors: 'sweetlove',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 2.5,
        x: '(.75 + .25 * cos(v)) * cos(u)',
        y: '(.75 + .25 * cos(v)) * sin(u)',
        z: '.25 * sin(v) * cos(u / 2)',
        w: '.25 * sin(v) * sin(u / 2)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: true,
        uLoop: false,
        uResolution: 38,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: true,
        vLoop: true,
        vResolution: 38,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        visible: true,
        opacity: 0.4,
        blending: '1',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.2,
        blending: '2',
        linewidth: 2,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
    'Inverted Mobius Tube': {
      0: {
        shape: 'generateUVSurface',
        colors: 'onedarkterminator',
        zFov: 90,
        wFov: 90,
        cellSize: 100,
        scale: 2.5,
        x: '(.25 + .75 * cos(v)) * cos(u)',
        y: '(.25 + .75 * cos(v)) * sin(u)',
        z: '.75 * sin(v) * cos(u / 2)',
        w: '.75 * sin(v) * sin(u / 2)',
        uMin: 0,
        uMax: 2 * Math.PI,
        uInclusive: true,
        uLoop: false,
        uResolution: 38,
        vMin: 0,
        vMax: 2 * Math.PI,
        vInclusive: true,
        vLoop: true,
        vResolution: 38,
        wMin: 0,
        wMax: 2 * Math.PI,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withUCells: true,
        withVCells: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 5,
        xz: 5,
        xw: 5,
        yz: 5,
        yw: 5,
        zw: 5,
      },
      3: {
        visible: true,
        opacity: 0.2,
        blending: '2',
        depthWrite: false,
        wireframe: false,
      },
      4: {
        visible: true,
        opacity: 0.1,
        blending: '1',
        linewidth: 1,
        depthWrite: false,
      },
      5: {
        visible: false,
      },
    },
  },
  preset: 'Tesseract',
  closed: false,
  folders: {
    '4d rotation': {
      preset: 'Default',
      closed: true,
      folders: {},
    },
    '4d rotation speed': {
      preset: 'Default',
      closed: false,
      folders: {},
    },
    Cell: {
      preset: 'Default',
      closed: false,
      folders: {},
    },
    Edge: {
      preset: 'Default',
      closed: false,
      folders: {},
    },
    Vertice: {
      preset: 'Default',
      closed: true,
      folders: {},
    },
    Debug: {
      preset: 'Default',
      closed: true,
      folders: {},
    },
  },
}
