export default {
  remembered: {
    'Tesseract (8-cell)': {
      0: {
        shape: 'tesseract',
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: 2,
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.04,
        colorGenerator: 'cell',
        blending: 2,
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Sliced Tesseract': {
      0: {
        shape: 'tesseract',
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uResolution: 8,
        uInclusive: false,
        uLoop: true,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vResolution: 8,
        vInclusive: false,
        vLoop: true,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wResolution: 8,
        wInclusive: false,
        wLoop: true,
        withWCells: true,
        colors: 'pear',
        environment: 'none',
        mode: 'cross-section',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 5,
        yz: 0,
        yw: 5,
        zw: 5,
      },
      3: {
        slice: 0,
        speed: 0,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 1,
        premultipliedAlpha: false,
        colorGenerator: 'cell',
        blending: '1',
        material: 'physical',
        reflectivity: 1,
        refractionRatio: 0,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 1,
        clearcoat: 1,
        clearcoatRoughness: 0.52,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.9,
        colorGenerator: 'cell',
        blending: '1',
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Pentachoron (5-cell)': {
      0: {
        shape: 'pentachoron',
        colors: 'material',
        premultipliedAlpha: false,
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.15,
        colorGenerator: 'cell',
        blending: '2',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.04,
        colorGenerator: 'cell',
        blending: 2,
        linewidth: 1,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Hexadecachoron (16-cell)': {
      0: {
        shape: 'hexadecachoron',
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.08,
        colorGenerator: 'cell',
        blending: '2',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.05,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Icositetrachoron (24-cell)': {
      0: {
        shape: 'icositetrachoron',
        colors: 'material',
        premultipliedAlpha: false,
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.15,
        colorGenerator: 'cell',
        blending: '1',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Hecatonicosachoron (120-cell)': {
      0: {
        shape: 'hecatonicosachoron',
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.05,
        colorGenerator: 'cell',
        blending: '2',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.05,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 1.25,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Sliced Hecatonicosachoron': {
      0: {
        shape: 'hecatonicosachoron',
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uResolution: 8,
        uInclusive: false,
        uLoop: true,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vResolution: 8,
        vInclusive: false,
        vLoop: true,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wResolution: 8,
        wInclusive: false,
        wLoop: true,
        withWCells: true,
        colors: 'rainbow',
        environment: 'none',
        mode: 'cross-section',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 3,
        xz: 3,
        xw: 3,
        yz: 3,
        yw: 3,
        zw: 3,
      },
      3: {
        slice: 0,
        speed: 0.3,
      },
      4: {
        visible: true,
        transparent: false,
        opacity: 1,
        premultipliedAlpha: false,
        colorGenerator: 'cell',
        blending: '0',
        material: 'phong',
        reflectivity: 0,
        refractionRatio: 0,
        shininess: 60,
        metalness: 0.5,
        roughness: 0,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: true,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 2,
        depthWrite: true,
        reuse: 'all',
        split: 'none',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Hexacosichoron (600-cell)': {
      0: {
        shape: 'hexacosichoron',
        colors: 'sweetlove',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '1',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 1,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Grand Antiprism': {
      0: {
        shape: 'grandAntiPrism',
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '1',
        material: 'physical',
        premultipliedAlpha: true,
        reflectivity: 1,
        refractionRatio: 0,
        shininess: 30,
        metalness: 0,
        roughness: 0.7,
        transmission: 0.97,
        clearcoat: 1,
        clearcoatRoughness: 0.7,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '1',
        linewidth: 1.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Sections of H4': {
      0: {
        shape: 'permutahedronH',
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uResolution: 8,
        uInclusive: false,
        uLoop: true,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vResolution: 8,
        vInclusive: false,
        vLoop: true,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wResolution: 8,
        wInclusive: false,
        wLoop: true,
        withWCells: true,
        colors: 'sweetlove',
        environment: 'none',
        mode: 'cross-section',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      3: {
        slice: 0,
        speed: 0.9,
      },
      4: {
        visible: true,
        transparent: false,
        opacity: 1,
        premultipliedAlpha: false,
        colorGenerator: 'cell',
        blending: '0',
        material: 'phong',
        reflectivity: 0,
        refractionRatio: 0,
        shininess: 30,
        metalness: 0,
        roughness: 0,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: true,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 2,
        depthWrite: true,
        reuse: 'all',
        split: 'none',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Cubic Pyramid': {
      0: {
        shape: 'cubicPyramid',
        colors: 'pear',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 5,
        xz: 5,
        xw: 10,
        yz: 5,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.3,
        colorGenerator: 'cell',
        blending: '1',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.5,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 2.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    SolidTesseract: {
      0: {
        shape: 'tesseract',
        colors: 'material',
        premultipliedAlpha: false,
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: 0,
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: true,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: false,
        transparent: true,
        opacity: 0.04,
        colorGenerator: 'cell',
        blending: 2,
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    '8 cubes': {
      0: {
        shape: 'tesseract',
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uResolution: 8,
        uInclusive: false,
        uLoop: true,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vResolution: 8,
        vInclusive: false,
        vLoop: true,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wResolution: 8,
        wInclusive: false,
        wLoop: true,
        withWCells: true,
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 119.91728416336377,
        wFov: 180,
        splitScale: 50,
        scale: 1.5,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 1,
        premultipliedAlpha: false,
        colorGenerator: 'cell',
        blending: '1',
        material: 'physical',
        reflectivity: 0.55,
        refractionRatio: 0,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 1,
        clearcoat: 1,
        clearcoatRoughness: 0.45,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.9,
        colorGenerator: 'cell',
        blending: '1',
        linewidth: 1.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Glome (3-sphere)': {
      0: {
        shape: 'glome',
        colors: 'natural',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.2,
        colorGenerator: 'cell',
        blending: '1',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'faces',
        split: 'cells',
      },
      5: {
        visible: false,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 0.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Ditorus (3-torus)': {
      0: {
        shape: 'diTorus',
        colors: 'rainbow',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uResolution: 8,
        uInclusive: false,
        uLoop: true,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vResolution: 8,
        vInclusive: false,
        vLoop: true,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wResolution: 8,
        wInclusive: false,
        wLoop: true,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.3,
        premultipliedAlpha: false,
        colorGenerator: 'cell',
        blending: '1',
        material: 'phong',
        reflectivity: 0,
        refractionRatio: 0.5,
        shininess: 40,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'faces',
        split: 'cells',
      },
      5: {
        visible: false,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Glome glass': {
      0: {
        shape: 'glome',
        colors: 'white',
        environment: 'ocean',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.3,
        colorGenerator: 'cell',
        blending: '1',
        material: 'phong',
        premultipliedAlpha: false,
        reflectivity: 1,
        refractionRatio: 0.5,
        shininess: 40,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'faces',
        split: 'cells',
      },
      5: {
        visible: false,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 1.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Glome minecraft': {
      0: {
        shape: 'glome',
        colors: 'sweetlove',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 10,
        xz: 10,
        xw: 10,
        yz: 10,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '0',
        material: 'phong',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 50,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: true,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: false,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 0.5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    "Klein's Bottle": {
      0: {
        shape: 'generateUVSurface',
        colors: 'zenburn',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: '0.75 * (cos(u / 2) * cos(v) - sin(u/2) * sin(2*v))',
        y: '0.75 * (sin(u / 2) * cos(v) + cos(u/2) * sin(2*v))',
        z: '0.75 * cos(u) * (1 + 0.001 * sin(v))',
        w: '0.75 * sin(u) * (1 + 0.001 * sin(v))',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: true,
        uLoop: false,
        uResolution: 38,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: true,
        vLoop: true,
        vResolution: 38,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 5,
        xz: 5,
        xw: 5,
        yz: 5,
        yw: 5,
        zw: 5,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        blending: '2',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '1',
        linewidth: 1,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Mobius Tube': {
      0: {
        shape: 'generateUVSurface',
        colors: 'rainbow',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: '(.75 + .25 * cos(v)) * cos(u)',
        y: '(.75 + .25 * cos(v)) * sin(u)',
        z: '.25 * sin(v) * cos(u / 2)',
        w: '.25 * sin(v) * sin(u / 2)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: true,
        uLoop: false,
        uResolution: 64,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: true,
        vLoop: true,
        vResolution: 27,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.4,
        colorGenerator: 'cell',
        blending: '1',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Inverted Mobius Tube': {
      0: {
        shape: 'generateUVSurface',
        colors: 'aap',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: '(.25 + .75 * cos(v)) * cos(u)',
        y: '(.25 + .75 * cos(v)) * sin(u)',
        z: '.75 * sin(v) * cos(u / 2)',
        w: '.75 * sin(v) * sin(u / 2)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: true,
        uLoop: false,
        uResolution: 64,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: true,
        vLoop: true,
        vResolution: 64,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 5,
        xz: 5,
        xw: 5,
        yz: 5,
        yw: 5,
        zw: 5,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.4,
        colorGenerator: 'cell',
        blending: '2',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.1,
        colorGenerator: 'cell',
        blending: '1',
        linewidth: 1,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Flat Glass Torus': {
      0: {
        shape: 'generateUVWHyperSurface',
        colors: 'white',
        environment: 'sunset',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(u)',
        y: 'sin(u)',
        z: 'cos(v)',
        w: 'sin(v)',
        uMin: 0,
        uMax: 12.566370614359172,
        uInclusive: false,
        uLoop: true,
        uResolution: 64,
        withUCells: false,
        vMin: 0,
        vMax: 12.566370614359172,
        vInclusive: false,
        vLoop: true,
        vResolution: 64,
        withVCells: false,
        wMin: 0,
        wMax: 12.566370614359172,
        wInclusive: false,
        wLoop: true,
        wResolution: 1,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '1',
        material: 'physical',
        premultipliedAlpha: false,
        reflectivity: 1,
        refractionRatio: 0,
        shininess: 0,
        metalness: 0,
        roughness: 0,
        transmission: 1,
        clearcoat: 1,
        clearcoatRoughness: 0.1,
        thickness: 1,
        ior: 1.5,
        depthWrite: true,
        wireframe: false,
        reuse: 'all',
        split: 'none',
      },
      5: {
        visible: false,
        transparent: true,
        opacity: 0.2,
        colorGenerator: 'cell',
        blending: '2',
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'Hecatonicosachoron Honeycomb': {
      0: {
        shape: 'hecatonicosachoron',
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.4787179045321385,
        colorGenerator: 'cell',
        blending: '1',
        material: 'phong',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 100,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.05,
        colorGenerator: 'cell',
        blending: '3',
        linewidth: 5,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'H4 NightSky': {
      0: {
        shape: 'permutahedronH',
        colors: 'onedarkterminator',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 10,
        scale: 10,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 2,
        xz: 3,
        xw: 5,
        yz: 7,
        yw: 11,
        zw: 13,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '0',
        material: 'lambert',
        premultipliedAlpha: false,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 30,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: true,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: false,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '4',
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: false,
        opacity: 1,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    Jewel: {
      0: {
        shape: 'hexacosichoron',
        colors: 'rainbow',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283185307179586,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283185307179586,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283185307179586,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 1,
        colorGenerator: 'cell',
        blending: '5',
        material: 'physical',
        premultipliedAlpha: true,
        reflectivity: 0,
        refractionRatio: 0.98,
        shininess: 42,
        metalness: 0,
        roughness: 0.2,
        transmission: 0.95,
        clearcoat: 1,
        clearcoatRoughness: 0.35,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.01,
        colorGenerator: 'uniform',
        blending: '1',
        linewidth: 1,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: false,
        transparent: true,
        opacity: 0.25,
        colorGenerator: 'cell',
        size: 1,
        reuse: 'faces',
        split: 'none',
      },
    },
    'A4 Shiny': {
      0: {
        shape: 'permutahedronA',
        colors: 'natural',
        environment: 'none',
        mode: 'projection',
        zFov: 90,
        wFov: 90,
        splitScale: 99.9,
        scale: 1,
        x: 'cos(v) * cos(u)',
        y: 'cos(v) * sin(u)',
        z: 'sin(v) * cos(u)',
        w: 'sin(v) * sin(u)',
        uMin: 0,
        uMax: 6.283,
        uInclusive: false,
        uLoop: true,
        uResolution: 8,
        withUCells: true,
        vMin: 0,
        vMax: 6.283,
        vInclusive: false,
        vLoop: true,
        vResolution: 8,
        withVCells: true,
        wMin: 0,
        wMax: 6.283,
        wInclusive: false,
        wLoop: true,
        wResolution: 8,
        withWCells: true,
      },
      1: {
        xy: 0,
        xz: 0,
        xw: 0,
        yz: 0,
        yw: 0,
        zw: 0,
      },
      2: {
        xy: 0,
        xz: 0,
        xw: 10,
        yz: 0,
        yw: 10,
        zw: 10,
      },
      3: {
        slice: 0,
        speed: 1,
      },
      4: {
        visible: true,
        transparent: true,
        opacity: 0.3,
        colorGenerator: 'cell',
        blending: '1',
        material: 'phong',
        premultipliedAlpha: false,
        reflectivity: 0.5,
        refractionRatio: 0,
        shininess: 60,
        metalness: 0.5,
        roughness: 1,
        transmission: 0,
        clearcoat: 0,
        clearcoatRoughness: 0,
        thickness: 0,
        ior: 1.2,
        depthWrite: false,
        wireframe: false,
        reuse: 'none',
        split: 'cells',
      },
      5: {
        visible: true,
        transparent: true,
        opacity: 0.8,
        colorGenerator: 'cell',
        blending: '1',
        linewidth: 2,
        depthWrite: false,
        reuse: 'faces',
        split: 'cells',
      },
      6: {
        visible: true,
        transparent: true,
        opacity: 0.5,
        colorGenerator: 'cell',
        size: 0.5,
        reuse: 'faces',
        split: 'none',
      },
    },
  },
  preset: 'Tesseract (8-cell)',
  closed: false,
  folders: {
    'Main config': {
      preset: 'Default',
      closed: true,
      folders: {},
    },
    'UVW parameters': {
      preset: 'Default',
      closed: true,
      folders: {
        U: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
        V: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
        W: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
      },
    },
    Transformations: {
      preset: 'Default',
      closed: true,
      folders: {
        '4d rotation': {
          preset: 'Default',
          closed: true,
          folders: {},
        },
        '4d rotation speed': {
          preset: 'Default',
          closed: true,
          folders: {},
        },
        Slice: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
      },
    },
    Rendering: {
      preset: 'Default',
      closed: true,
      folders: {
        Cells: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
        Edges: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
        Vertices: {
          preset: 'Default',
          closed: true,
          folders: {},
        },
      },
    },
  },
}
